name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7
    - name: Run pre-commit
      run: |
        pip install pre-commit
        pre-commit run --all-files
